name: galacticdrift # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Galactic Drift
summary: Immersive space exploration game set in a vast, procedurally generated universe.
description: As you traverse the cosmos, you'll uncover ancient artifacts, engage in thrilling dogfights with space pirates, and forge alliances with diverse alien species.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  galacticdrift:
    command: bin/galacticdrift-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  galacticdrift:
    plugin: dump
    source: .
    organize:
      galacticdrift-bin: bin/
